name: Build and Deploy al-folio

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # 安装 Python（用于提供 jupyter CLI）
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 安装 jupyter/nbconvert（提供 `jupyter nbconvert` 命令）
      - name: Install Jupyter CLI
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      # （如果后面遇到 pandoc 报错，再加下面两行）
      # - name: Install pandoc (only if needed)
      #   run: sudo apt-get update && sudo apt-get install -y pandoc

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"     # 或者删掉这一行，自动读取 .ruby-version
          bundler-cache: true

      - name: Install deps
        run: bundle install --without development

      - name: Build site
        run: bundle exec jekyll build --trace

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4